# Generated by Django 5.0 on 2023-12-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('Roll', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=50)),
                ('Address', models.TextField()),
            ],
        ),
    ]
