# Generated by Django 5.0 on 2023-12-31 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('posts', '0002_remove_post_author_post_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
