# Generated by Django 5.0 on 2023-12-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='FatherName',
            field=models.TextField(default='Wali'),
        ),
    ]
